language: python

python:
    - 2.7

branches:
  only:
    - develop

before_install:

install:
    - pip install setuptools
    - cd src; python setup.py install

script:
    - python manage.py db upgrade
