from flask import render_template, flash, redirect, session, url_for, request, g, make_response
from flask.ext.login import login_user, logout_user, current_user, login_required

from app import app, db, lm, oid, plugins

from forms import LoginForm
from models import User, ROLE_USER, ROLE_ADMIN

from pprint import pprint

import yaml

from util.figshare import figshare_authorize, get_auth_url, validate_oauth_verifier, get_articles, get_article, update_article, FigshareEmptyResponse, FigshareNoTokenError
from util.rdf import get_rdf, get_trig
from util.dropbox_client import dropbox_authorize, dropbox_callback

@lm.user_loader
def load_user(id):
    return User.query.get(int(id))

@app.before_request
def before_request():
    app.logger.debug(request.path)
    g.user = current_user
    

@app.route('/')
@app.route('/index')
def index():
    return render_template('landing.html', 
                          user=g.user)
    

@app.route('/dashboard')
@login_required
def dashboard():
    """If this session has not yet been initialized (i.e. we don't yet have an oauth_token from Figshare), 
    it starts up the three-legged authentication procedure for OAuth v1.
    
    Otherwise, it initializes the session variable with the article details of the Figshare author
    
    """
    
    if g.user.oauth_token == None or g.user.oauth_token == "" :
        """This user does not yet have an oauth_token, so redirect to the authorization page"""
        
        return redirect(url_for('figshare_authorize'))
    else :
        """
        This is where we retrieve all articles of the Figshare author who provided the authentication.
        """
        
        try :
            get_articles()
            
            return render_template('articles.html', 
                               raw = str(session['items']),
                               results = session['items'], 
                               plugins = plugins.values(),
                               user = g.user)
        except FigshareEmptyResponse as e :
            app.logger.error(e)
            return redirect(url_for('figshare_authorize'))
        except FigshareNoTokenError as e :
            app.logger.error(e)
            return redirect(url_for('figshare_authorize'))
        except Exception as e :
            app.logger.error(e)
            return render_template('error.html', 
                                   message = "Error retrieving articles!: " + e.message, 
                                   user=g.user)
        

@app.route('/refresh/<article_id>')
@login_required
def refresh_article(article_id):
    article = get_article(article_id)
    
    app.logger.debug(article)
    
    return render_template('article_details.html',
                           i = article,
                           user = g.user )


@app.route('/rdf/<article_id>', methods = ['POST'])
@login_required
def download_rdf(article_id):
    checked_urls = request.form.getlist('url')
    
    graphTrix = get_trig(article_id, checked_urls)
    
    response = make_response(graphTrix)
    response.mimetype = "application/trig"
    response.contenttype = "application/trig"
    response.headers.add('Content-Disposition', 'attachment; filename={}.trig'.format(article_id))

    return response


@app.route('/figshare/<article_id>', methods = ['POST'])
@login_required
def update_figshare(article_id):
    checked_urls = request.form.getlist('url')
    
    update_article(article_id, checked_urls)
            
    # Reset the URLs generated by the application
    session[article_id] = []
    session.modified = True
    
    return "Ok"



@app.route('/clear')
def clear_session_data():
    app.logger.debug("Logging out user")
    logout_user()
    app.logger.debug("Clearing session data")
    session.clear()
    app.logger.debug("Session data cleared")
    return render_template('warning.html', 
                           message = "Session data cleared!",
                           user = g.user)


@app.route('/dropbox')
@login_required
def dropbox():
    if g.user.dropbox_access_token_key == None or g.user.dropbox_access_token_key == "" :
        """This user does not yet have an oauth_token, so redirect to the dropbox authorization page"""
        
        return redirect(url_for('dropbox_authorize'))
    
    print url_for('dropbox_callback')
    return render_template("dropbox.html", user = g.user)


## LOGIN Stuff below

@app.route('/login', methods = ['GET', 'POST'])
@oid.loginhandler
def login():
    if g.user is not None and g.user.is_authenticated():
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        session['remember_me'] = form.remember_me.data
        return oid.try_login(form.openid.data, ask_for = ['fullname', 'email'])
    return render_template('login.html', 
        form = form,
        providers = app.config['OPENID_PROVIDERS'])

@oid.after_login
def after_login(resp):
    if resp.email is None or resp.email == "":
        flash('Invalid login. Please try again.')
        redirect(url_for('index'))
        
    user = User.query.filter_by(email = resp.email).first()
    
    if user is None:
        app.logger.warning(resp)
        
        nickname = resp.fullname
        
        if nickname is None or nickname == "":
            nickname = resp.email.split('@')[0]
        user = User(nickname = nickname, email = resp.email, role = ROLE_USER)
        db.session.add(user)
        db.session.commit()
    
    remember_me = False
    
    if 'remember_me' in session:
        remember_me = session['remember_me']
        session.pop('remember_me', None)
    
    login_user(user, remember = remember_me)
    return redirect(request.args.get('next') or url_for('index'))

@app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))